export const RestaurantList = [
    {
      info: {
        id: "409724",
        name: "Dawat Biryani House",
        cloudinaryImageId: "swxfbq3xcbitulrztmfa",
        locality: "Radhakrishna Nagar",
        areaName: "Bhosari",
        costForTwo: "₹300 for two",
        cuisines: ["Biryani", "Indian"],
        avgRating: 3.8,
        parentId: "14259",
        avgRatingString: "3.8",
        totalRatingsString: "100+",
        sla: {
          deliveryTime: 31,
          lastMileTravel: 2.7,
          serviceability: "SERVICEABLE",
          slaString: "31 mins",
          lastMileTravelString: "2.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 23:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/dawat-biryani-house-radhakrishna-nagar-bhosari-pune-409724",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "33328",
        name: "Faasos - Wraps, Rolls & Shawarma",
        cloudinaryImageId: "af33b81798b11deba338e94b7585d348",
        locality: "NEAR INDRAYANI NAGAR",
        areaName: "Bhosari",
        costForTwo: "₹200 for two",
        cuisines: [
          "Kebabs",
          "Fast Food",
          "Snacks",
          "American",
          "Healthy Food",
          "Desserts",
          "Beverages",
        ],
        avgRating: 4.2,
        parentId: "21809",
        avgRatingString: "4.2",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 4.5,
          serviceability: "SERVICEABLE",
          slaString: "35 mins",
          lastMileTravelString: "4.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 23:59:00",
          opened: true,
        },
        badges: {
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {
              badgeObject: [
                {
                  attributes: {
                    description: "",
                    fontColor: "#7E808C",
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "options available",
                  },
                },
              ],
            },
          },
        },
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹110",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/faasos-wraps-rolls-and-shawarma-near-indrayani-nagar-bhosari-pune-33328",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "17360",
        name: "Subway",
        cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
        locality: "Shivar Garden Road",
        areaName: "Pimple Saudagar",
        costForTwo: "₹350 for two",
        cuisines: [
          "Fast Food",
          "Healthy Food",
          "Salads",
          "Snacks",
          "Desserts",
          "Beverages",
        ],
        avgRating: 4.4,
        parentId: "2",
        avgRatingString: "4.4",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 37,
          lastMileTravel: 5.9,
          serviceability: "SERVICEABLE",
          slaString: "37 mins",
          lastMileTravelString: "5.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 23:45:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/subway-shivar-garden-road-pimple-saudagar-pune-17360",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "62973",
        name: "LunchBox - Meals and Thalis",
        cloudinaryImageId: "kedmnofdk5owwlqjzxr0",
        locality: "NEAR INDRAYANI NAGAR",
        areaName: "Bhosari",
        costForTwo: "₹200 for two",
        cuisines: [
          "Biryani",
          "North Indian",
          "Punjabi",
          "Healthy Food",
          "Desserts",
          "Beverages",
        ],
        avgRating: 4.2,
        parentId: "4925",
        avgRatingString: "4.2",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 34,
          lastMileTravel: 4.5,
          serviceability: "SERVICEABLE",
          slaString: "34 mins",
          lastMileTravelString: "4.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 23:59:00",
          opened: true,
        },
        badges: {
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {
              badgeObject: [
                {
                  attributes: {
                    description: "",
                    fontColor: "#7E808C",
                    iconId: "guiltfree/GF_Logo_android_3x",
                    shortDescription: "options available",
                  },
                },
              ],
            },
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/lunchbox-meals-and-thalis-near-indrayani-nagar-bhosari-pune-62973",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "740798",
        name: "Atithi Veg",
        cloudinaryImageId: "9f68d674b13db65239625285d765cd64",
        locality: "Pune Nashik road",
        areaName: "Bhosari",
        costForTwo: "₹400 for two",
        cuisines: [
          "North Indian",
          "Chinese",
          "South Indian",
          "Continental",
          "Fast Food",
          "Beverages",
          "Ice Cream",
          "Desserts",
        ],
        avgRating: 4.1,
        veg: true,
        parentId: "37603",
        avgRatingString: "4.1",
        totalRatingsString: "20+",
        sla: {
          deliveryTime: 33,
          lastMileTravel: 2.5,
          serviceability: "SERVICEABLE",
          slaString: "33 mins",
          lastMileTravelString: "2.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-17 00:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        isNewlyOnboarded: true,
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/atithi-veg-nashik-road-bhosari-pune-740798",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "126758",
        name: "Sai Restaurant",
        cloudinaryImageId: "bnbzkesrbvoc1lkjcqiv",
        locality: "Nehru nagar",
        areaName: "Pimpri",
        costForTwo: "₹400 for two",
        cuisines: [
          "North Indian",
          "Maharashtrian",
          "Chinese",
          "Biryani",
          "Mughlai",
        ],
        avgRating: 3.8,
        parentId: "18881",
        avgRatingString: "3.8",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 29,
          lastMileTravel: 2,
          serviceability: "SERVICEABLE",
          slaString: "29 mins",
          lastMileTravelString: "2.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 23:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          discountTag: "FLAT DEAL",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/sai-restaurant-nehru-nagar-pimpri-pune-126758",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "428741",
        name: "Upwas Uphargruha",
        cloudinaryImageId: "118e397db21459271dec04fe78f48752",
        locality: "Indrayani Nagar, Bhosari",
        areaName: "Bhosari",
        costForTwo: "₹150 for two",
        cuisines: ["Snacks", "Street Food"],
        avgRating: 3.6,
        veg: true,
        parentId: "239073",
        avgRatingString: "3.6",
        totalRatingsString: "100+",
        sla: {
          deliveryTime: 34,
          lastMileTravel: 2.5,
          serviceability: "SERVICEABLE",
          slaString: "34 mins",
          lastMileTravelString: "2.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 16:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/upwas-uphargruha-indrayani-nagar-bhosari-pune-428741",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "773523",
        name: "Hotel Maharaja",
        cloudinaryImageId: "334f5721fd2cb52b988758bbbb6246a8",
        locality: "Pimpri",
        areaName: "PCMC",
        costForTwo: "₹300 for two",
        cuisines: ["Indian", "Chinese"],
        parentId: "100047",
        avgRatingString: "NEW",
        sla: {
          deliveryTime: 27,
          lastMileTravel: 1.3,
          serviceability: "SERVICEABLE",
          slaString: "27 mins",
          lastMileTravelString: "1.3 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 15:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "30% OFF",
          subHeader: "UPTO ₹150",
          discountTag: "SAVE BIG",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        isNewlyOnboarded: true,
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/hotel-maharaja-pimpri-pcmc-pune-773523",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "136427",
        name: "Simply South",
        cloudinaryImageId: "yrur1ktgsf8owltx7do1",
        locality: "Alandi Road",
        areaName: "Bhosari",
        costForTwo: "₹200 for two",
        cuisines: [
          "South Indian",
          "North Indian",
          "Chinese",
          "Punjabi",
          "Tandoor",
          "Chaat",
          "Sweets",
        ],
        avgRating: 4.2,
        veg: true,
        parentId: "864",
        avgRatingString: "4.2",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 32,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "32 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 23:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹40",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/simply-south-alandi-road-bhosari-pune-136427",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "382576",
        name: "Chopstix",
        cloudinaryImageId: "a8tyuj9ts1rtnpjfenb0",
        locality: "Pimpri-Bhosari Road",
        areaName: "Pimpri",
        costForTwo: "₹300 for two",
        cuisines: ["Street Food", "Chinese", "Indian"],
        avgRating: 3.8,
        parentId: "2623",
        avgRatingString: "3.8",
        totalRatingsString: "9",
        sla: {
          deliveryTime: 32,
          lastMileTravel: 2.8,
          serviceability: "SERVICEABLE",
          slaString: "32 mins",
          lastMileTravelString: "2.8 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 23:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/chopstix-bhosari-road-pimpri-pune-382576",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "552668",
        name: "Chitale Bandhu Mithaiwale",
        cloudinaryImageId: "ewfmd6wzs88aewcoyrxm",
        locality: "Alandi Road",
        areaName: "Bhosari",
        costForTwo: "₹450 for two",
        cuisines: ["Sweets", "Snacks"],
        avgRating: 4.6,
        veg: true,
        parentId: "10773",
        avgRatingString: "4.6",
        totalRatingsString: "100+",
        sla: {
          deliveryTime: 27,
          lastMileTravel: 2.7,
          serviceability: "SERVICEABLE",
          slaString: "27 mins",
          lastMileTravelString: "2.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 20:30:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "v1695133679/badges/Pure_Veg111.png",
              description: "pureveg",
            },
          ],
        },
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "pureveg",
                    imageId: "v1695133679/badges/Pure_Veg111.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/chitale-bandhu-mithaiwale-alandi-road-bhosari-pune-552668",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "648990",
        name: "FNP Cakes By Ferns N Petals",
        cloudinaryImageId: "57f39df3b1e192cb54999ffbbdf40bf8",
        locality: "Vikas Colony",
        areaName: "Landewadi",
        costForTwo: "₹499 for two",
        cuisines: ["Bakery", "Desserts"],
        avgRating: 4.2,
        veg: true,
        parentId: "339638",
        avgRatingString: "4.2",
        totalRatingsString: "20+",
        sla: {
          deliveryTime: 29,
          lastMileTravel: 1.6,
          serviceability: "SERVICEABLE",
          slaString: "29 mins",
          lastMileTravelString: "1.6 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 22:50:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "v1695133679/badges/Pure_Veg111.png",
              description: "pureveg",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "pureveg",
                    imageId: "v1695133679/badges/Pure_Veg111.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/fnp-cakes-by-ferns-n-petals-vikas-colony-landewadi-pune-648990",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "516165",
        name: "Punjabi Rasoi",
        cloudinaryImageId: "clkxkjity6az5jahkpha",
        locality: "Datta Mandir Road",
        areaName: "PIMPRI",
        costForTwo: "₹300 for two",
        cuisines: ["North Indian", "Chinese", "Indian"],
        avgRating: 3.3,
        parentId: "1270",
        avgRatingString: "3.3",
        totalRatingsString: "100+",
        sla: {
          deliveryTime: 30,
          lastMileTravel: 1.7,
          serviceability: "SERVICEABLE",
          slaString: "30 mins",
          lastMileTravelString: "1.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 15:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "60% OFF",
          subHeader: "UPTO ₹120",
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/punjabi-rasoi-datta-mandir-road-pimpri-pune-516165",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "577878",
        name: "Naadbramha Idli",
        cloudinaryImageId: "4f0c184c5b030e6065ceee84093b1b12",
        locality: "Lande Wadi",
        areaName: "Bhosari",
        costForTwo: "₹100 for two",
        cuisines: ["South Indian"],
        avgRating: 4.7,
        veg: true,
        parentId: "251339",
        avgRatingString: "4.7",
        totalRatingsString: "20+",
        sla: {
          deliveryTime: 26,
          lastMileTravel: 1.2,
          serviceability: "SERVICEABLE",
          slaString: "26 mins",
          lastMileTravelString: "1.2 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 20:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/naadbramha-idli-lande-wadi-bhosari-pune-577878",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
    {
      info: {
        id: "748012",
        name: "Ribbons And Balloons - The Cake Shop",
        cloudinaryImageId: "6023adff185062866c83d892cec921bc",
        locality: "Sant Tukaram Nagar",
        areaName: "PCMC",
        costForTwo: "₹199 for two",
        cuisines: ["Bakery"],
        avgRating: 2.5,
        veg: true,
        parentId: "169284",
        avgRatingString: "2.5",
        totalRatingsString: "6",
        sla: {
          deliveryTime: 20,
          lastMileTravel: 1.6,
          serviceability: "SERVICEABLE",
          slaString: "20 mins",
          lastMileTravelString: "1.6 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-16 22:30:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "v1695133679/badges/Pure_Veg111.png",
              description: "pureveg",
            },
          ],
        },
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "pureveg",
                    imageId: "v1695133679/badges/Pure_Veg111.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        orderabilityCommunication: {
          title: {},
          subTitle: {},
          message: {},
          customIcon: {},
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        isNewlyOnboarded: true,
        restaurantOfferPresentationInfo: {},
      },
      analytics: {
        context: "seo-data-db84105d-3b3c-4794-8f8e-22a2b9764ba2",
      },
      cta: {
        link: "https://www.swiggy.com/restaurants/ribbons-and-balloons-the-cake-shop-sant-tukaram-nagar-pcmc-pune-748012",
        text: "RESTAURANT_MENU",
        type: "WEBLINK",
      },
      widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
    },
  ];
  